### ISSUE TITLE
"Content-encoding: mi-sha256" missing from §4.2 Signature Example

### ISSUE THREAD

**Issue by manger** [martinthomson/http-mice#1]
Need a "content-encoding: mi-sha256" header on the signature example. The MI header conveys an integrity check of the whole content, but isn't a signal that the content has been changed (to include hashes).

The simple example (§4.1) might not need a Content-Encoding header as (this version of) MICE doesn’t actually change the payload as it is shorter than the 4096-byte record size. Might be worth adding a Content-Encoding header anyway.

**Comment by martinthomson** [comment]
I think that it might be better to include `content-encoding` on both.  Thanks for picking that up.
